# Generated by Django 5.1.2 on 2024-11-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ka',
        ),
    ]
