# Generated by Django 5.1.2 on 2024-11-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_name_en_category_name_ka_category_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ka',
        ),
    ]
