# Generated by Django 5.1.2 on 2024-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ka',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_en',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_ka',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='created_at_en',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='created_at_ka',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description_ka',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='imageUrl_en',
            field=models.URLField(blank=True, null=True, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='imageUrl_ka',
            field=models.URLField(blank=True, null=True, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_ka',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='is_active_ka',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='name_ka',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price_en',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price_ka',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='quantity_en',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='quantity_ka',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='updated_at_en',
            field=models.DateField(auto_now=True, null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='updated_at_ka',
            field=models.DateField(auto_now=True, null=True, verbose_name='updated at'),
        ),
    ]
