# Generated by Django 5.1.2 on 2024-11-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_brand_name_en_brand_name_ka_producttag_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='created_at_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='imageUrl_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='imageUrl_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='is_active_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='quantity_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='quantity_ka',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='updated_at_en',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='updated_at_ka',
        ),
    ]
