# Generated by Django 5.1.2 on 2024-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_smartphone_created_at_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ka',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
    ]
